### ISSUE TITLE
Need to update to 1.2.1

### ISSUE THREAD

**Issue by justin808** [shakacode/jquery-ujs#1]
https://github.com/rails/jquery-ujs/tree/v1.2.1

@callumacrae Any chance that you can give us a hand with this?

**Comment by justin808** [comment]
@callumacrae give me the word if you're too busy and I'll do the update this weekend.

**Comment by lfittl** [comment]
@justin808 I assume this update happened, judging from 1.2.1 being on npm?

**Comment by justin808** [comment]
yes
